# Site settings
title: "Audacious Fox"
email: "comments@dreger.me"
description: "Liberal arts, in your browser."
url: "http://audaciousfox.com" 
permalink: /:year/:month/:day/:title.html
timezone: America/New_York
url_icon: '&#8984;'
url_icon: '&#9650;'

# Build settings
markdown: kramdown
 
highlighter: pygments
excerpt_separator: "<!-- more -->"

gems:
  - jekyll-sitemap

defaults:
  -
    scope:
      path: "links"
    values:
      layout: "post"
      category: links
  -
    scope:
      path: "articles"
    values:
      layout: "post"
      category: articles
