# Site settings
title: "Audacious Fox"
email: "comments@dreger.me"
description: "Framing technology, design, and gaming in a concise way."
url: "http://audaciousfox.net" 
timezone: America/New_York
icon: '&#9724;&#65038;'
destination: html
# permalink: /archive/:title-:short_year:y_day

# Build settings
sass:
  style: compressed
markdown: kramdown
highlighter: rouge
excerpt_separator: "<!-- more -->"

kramdown:
  auto_ids:       true
  footnote_nr:    1
  entity_output:  as_char
  toc_levels:     1..6
  smart_quotes:   lsquo,rsquo,ldquo,rdquo
  input:          GFM
  hard_wrap:      false
  footnote_nr:    1
  footnote_backlink: "&#8617;&#65038;"

gems:
  - jekyll-sitemap
  - jekyll-redirect-from

defaults:
  -
    scope:
      path: "_posts"
    values:
      layout: "post"
      category: articles
      permalink: /:year/:month/:title

  -
    scope:
      path: "_posts/linked"
    values:
      category: linked
      layout: "post"
      permalink: /linked/:year/:month/:day/:title
