# Site settings
title: "Audacious Fox"
email: "comments@dreger.me"
description: "Writing the web column I want to read."
url: "http://audaciousfox.com" # the base hostname & protocol for your site
permalink: posts/:short_year:month:day-:title.html
timezone: America/New_York

# Build settings
markdown: kramdown

highlighter: pygments
excerpt_separator: "<!-- more -->"

gems:
  - jekyll-sitemap
  # - jekyll-archives

defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
      category: post
  -
    scope:
      path: "signals"
      type: "posts"
    values:
      category: signals

jekyll-archives:
  enabled: [year, month, day]
  layout: 'default' #'archive'
  permalinks:
    year: '/:year/'
    month: '/:year/:month/'
    day: '/:year/:month/:day/'
