# Site settings
title: "Audacious Fox"
email: "comments@dreger.me"
description: "Liberal arts, in your browser."
url: "http://audaciousfox.com" 
timezone: America/New_York
url_icon: '&#9650;'

# Build settings
sass:
    style: compressed
markdown: kramdown 
highlighter: pygments
excerpt_separator: "<!-- more -->"

gems:
  - jekyll-sitemap
  - jekyll-redirect-from

defaults:
  -
    scope:
      path: "_posts/briefings"
    values:
      category: briefings
      layout: "post"
      permalink: /linked/:year/:month/:day/:title
  -
    scope:
      path: "_posts/articles"
    values:
      layout: "post"
      category: articles
      permalink: /:year/:month/:title
