# Site settings
title: "Audacious Fox"
email: "comments@dreger.me"
description: "Liberal arts, in your browser."
url: "http://audaciousfox.com" 
permalink: /:year/:month/:day/:title.html
timezone: America/New_York
url_icon: '&#9650;'

# Build settings
sass:
    style: compressed
markdown: kramdown 
highlighter: pygments
excerpt_separator: "<!-- more -->"

gems:
  - jekyll-sitemap

defaults:
  -
    scope:
      path: "briefings"
    values:
      category: briefings
      layout: "post"
  -
    scope:
      path: "articles"
    values:
      layout: "post"
      category: articles
