# Site settings
title: "Audacious Fox"
email: "comments@dreger.me"
description: "Liberal arts, in your browser."
url: "http://audaciousfox.com" 
timezone: America/New_York
icon: '&#9650;'

# Build settings
sass:
  style: compressed
markdown: kramdown 
highlighter: rouge
excerpt_separator: "<!-- more -->"

gems:
  - jekyll-sitemap
  - jekyll-redirect-from

defaults:
  -
    scope:
      path: "_posts"
    values:
      layout: "post"
      category: articles
      permalink: /:year/:title

  -
    scope:
      path: "_posts/briefings"
    values:
      category: briefings
      layout: "post"
      permalink: /briefings/:year/:title
