# Site settings
title: Audacious Fox
email: "comments@dreger.me"
description: "Writing the web column I want to read."
url: "http://audaciousfox.com" # the base hostname & protocol for your site
permalink: /archives/:year:month:day-:title.html

# Build settings
markdown: kramdown

gems:
  - jekyll-sitemap

defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
