# Site settings
title: "Audacious Fox"
email: "comments@dreger.me"
description: "Liberal arts, in your browser."
url: "http://audaciousfox.com" 
permalink: /:year/:month/:day/:title.html
timezone: America/New_York
url_icon: '&#8984;'
url_icon: '&#9650;'

# Build settings
markdown: kramdown

highlighter: pygments
excerpt_separator: "<!-- more -->"


gems:
  - jekyll-sitemap
  # - jekyll-archives

defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
      category: post
  -
    scope:
      path: "links"
      type: "posts"
    values:
      category: links
  -
    scope:
      path: "columns"
      type: "posts"
    values:
      category: columns


jekyll-archives:
  enabled: [year, month, day]
  layout: 'default' #'archive'
  permalinks:
    year: '/:year/'
    month: '/:year/:month/'
    day: '/:year/:month/:day/'
