baseurl             = 'https://audaciousfox.net'
title               = 'Audacious Fox'
languageCode        = 'en-us'
MetaDataFormat      = 'yaml'
disableKinds        = ['RSS']
uglyurls            = false
publishdir          = 'html'
pluralizelisttitles = false
footnoteReturnLinkContents = '↩&#65038;'

[sitemap]
  changefreq = 'monthly'
  priority = 0.5
  filename = 'sitemap.xml'

[author]
  name = 'K.Q. Dreger'

[permalinks]
  archive = '/:year/:filename'
  linked = '/linked/:year/:filename'

[blackfriday]
  smartypants = true
  fractions = true
  plainIDAnchors = true

[params]
  icon = '&#9650;&#65038;'
