baseurl = "https://audaciousfox.net"
title = "Audacious Fox"
languageCode = "en-us"
MetaDataFormat = "yaml"
disableRSS = true
disableSitemap = false
uglyurls = false
publishdir = "html"
footnoteReturnLinkContents = "↩"

[sitemap]
  changefreq = "monthly"
  priority = 0.5
  filename = "sitemap.xml"

[author]
  name = "K.Q. Dreger"

[permalinks]
  archive = "/:year/:month/:filename"
  linked = "/linked/:year/:month/:day/:filename"

[blackfriday]
  smartypants = true
  fractions = true
  plainIDAnchors = true

[params]
  icon = '&#9724;&#65038;'
