baseurl             = 'https://audaciousfox.net'
title               = 'Audacious Fox'
languageCode        = 'en-us'
MetaDataFormat      = 'yaml'
disableKinds        = ['RSS', 'taxonomy', 'taxonomyTerm']
uglyurls            = false
publishdir          = 'html'
pluralizelisttitles = false
footnoteReturnLinkContents = '↩&#65038;'
titleCaseStyle = "AP"

[taxonomies]
  tag = "tags"

[sitemap]
  changefreq = 'monthly'
  priority = 0.5
  filename = 'sitemap.xml'

[author]
  name = 'K.Q. Dreger'
  url = 'https://twitter.com/dreger'

[permalinks]
  archive = '/:year/:filename'
  linked = '/linked/:year/:filename'

[blackfriday]
  smartypants = true
  fractions = true
  plainIDAnchors = true

[params]
  icon = '&#9650;&#65038;'


[mediaTypes]
  [mediaTypes."application/xml"]
    suffixes = ["xml"]
  [mediaTypes."application/json"]
    suffixes = ["json"]

[outputFormats.Json]
  mediaType = "application/json"
  baseName = "feeds/main"
  isPlainText = false

[outputFormats.Xml]
  mediaType = "application/xml"
  baseName = "feeds/main"
  isPlainText = false

[outputs]
  home = [ "HTML", "Xml", "Json" ]